# Generated by Django 4.1 on 2023-06-22 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=10000)),
                ("description", models.CharField(max_length=100000)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=10000)),
                (
                    "image",
                    models.FileField(
                        default=None,
                        upload_to="event/images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "png",
                                    "jpeg",
                                    "docx",
                                    "txt",
                                    "mp4",
                                    "ts",
                                    "avi",
                                ]
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
