# Generated by Django 4.1 on 2023-06-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_event"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="image",),
        migrations.AddField(
            model_name="event", name="time", field=models.TimeField(default=None),
        ),
    ]
